#! ruby
require 'test/unit'
require 'yaml_zlib_blowfish'
require 'gtk2passwordapp/account'
require 'gtk2passwordapp/accounts'

CONFIG = {
  CipherError: 'wut',
  AccountMiss: 'wut',
  AccountHit:  'wut',
}

class TestAccounts < Test::Unit::TestCase
  def test_accounts()
    assert_nothing_raised() do
      dumpfile = './test/dump.yzb'

      accounts = Gtk2PasswordApp::Accounts.new(dumpfile, 'ThePassphrase')
      assert_equal 0, accounts.names.length
      accounts.add('Vanilla')
      assert_equal 1, accounts.names.length
      accounts.add('Chocolate')
      assert_equal 2, accounts.names.length
      assert accounts.data.has_key?('Chocolate')
      refute accounts.data.has_key?('Strawberry')
      accounts.add('Strawberry')
      assert_equal 3, accounts.names.length
      assert accounts.data.has_key?('Strawberry')
      assert_raises(RuntimeError){ accounts.add('Strawberry') }
      accounts.delete('Vanilla')
      refute accounts.data.has_key?('Vanilla')
      assert_raises(RuntimeError){ accounts.get('Vanilla') }

      chocolate = accounts.get('Chocolate')
      assert_equal Gtk2PasswordApp::Account, chocolate.class
      vanilla = accounts.add('Vanilla')
      assert_equal Gtk2PasswordApp::Account, vanilla.class

      accounts.save

      accounts2 = Gtk2PasswordApp::Accounts.new(dumpfile, 'ThePassphrase')
      accounts2.load
      assert_equal 3, accounts2.names.length
      assert accounts2.data.has_key?('Chocolate')
      assert accounts2.data.has_key?('Strawberry')
      assert accounts2.data.has_key?('Vanilla')
      assert_equal ['Chocolate','Strawberry','Vanilla'], accounts2.names.sort

      assert_equal accounts.data, accounts2.data

      File.unlink dumpfile
    end
  end
end
