#! ruby
require 'test/unit'
require 'gtk2passwordapp/version'

class TestVersion < Test::Unit::TestCase
  def test_vesion()
    assert_nothing_raised() do
      version = '4.1.2'
      assert_equal(version, Gtk2passwordapp::VERSION)
      assert_equal(version, File.read('./data/VERSION').strip)
      vrsn = `ruby -I ./lib ./bin/gtk2passwordapp -v`.strip
      assert_equal(version, vrsn)
    end
  end
end
