#! ruby
require 'test/unit'

class TestVersion < Test::Unit::TestCase
  def test_vesion()
    assert_nothing_raised() do
      version = '5.2.1'
      assert_equal(version, File.read('./data/VERSION').strip)
      vrsn = `ruby -I ./lib ./bin/gtk2pwdV -v`.strip
      assert_equal(version, vrsn)
    end
  end
end
